### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by psvita123** [elpendor/accountswitcher#1]
Hello,
i need some help. this amazing app for vita was released that allowed to switch psn accounts on vita.
but now im not able to use it now.
i reinstalled the app becuz of a update, but now when i open the app the current account the app is showing is "not found".
and when i go to save current account this shows up.
you can`t save this account : profile cannot be found
im on 3.60 with latest henkaku with working psn.
pls can any one help
Username
psvita
Posts
17
Joined
Mon Oct 15, 2012 3:13 pm
Contact

**Comment by Kyogre** [comment]
Check that you didn't exit your account. If you exited no account will be found

**Comment by psvita123** [comment]
Exit from what my friend!!!!

**Comment by psvita123** [comment]
How can I exit my account
I didn't get ur point

**Comment by Kyogre** [comment]
If you exited from your current PSN account

**Comment by psvita123** [comment]
U mean to say I restored my system

**Comment by Kyogre** [comment]
no, I mean "you went to Settings -> PSN -> exit from account"

**Comment by psvita123** [comment]
Well I never exit my account but only do regularly swap memory cards

**Comment by psvita123** [comment]
What can I do to fix it

**Comment by psvita123** [comment]
Oh now I remember I once found out my PS vita to be not logged in
I will not have sign out purposely but maybe by mistake

**Comment by psvita123** [comment]
Is there any fix for this to add my account again to the app

**Comment by Kyogre** [comment]
you just need connect to internet and login to PSN (if you successfully logged in so PS Store will work for you). Then go to accountswitcher

**Comment by psvita123** [comment]
hello again
this what i did now:-
1- went to the app where it stilled showed no account even after logging into ps store.
2- went to unslave memory card which was sucessfull
3- Fully restored my vita without formatting
4- logged in with another psn account
5- went and installed henkaku
6- went to ps store to make sure psn is working and it is working
7- installed ur app again.
8- for the first 5 - 10 seconds it was showing my name in the account info instead of "no account".
9- as soon as i  clicked save current account it went back to no account found
PS:
What i found interesting was that my memory card was not formatted afterall even after switching account

**Comment by psvita123** [comment]
hey any fix for this
you have been extremly helpfull.

**Comment by psvita123** [comment]
if there is no fix you can tell so.....
atleast u can reply with something @Kyogre

**Comment by Kyogre** [comment]
I am not developer of accountswitcher, I am just ordinary user as you. I thought you called for dev so I didn't reply.

**Comment by psvita123** [comment]
you also faced this problem??

**Comment by Kyogre** [comment]
partially (I exited from account and understood that I forgot to save it before change to another one)
