### ISSUE TITLE
@elpendor

### ISSUE THREAD

**Issue by psvita123** [elpendor/accountswitcher#2]
Hello @elpendor,
i need some help. this amazing app for vita was released that allowed to switch psn accounts on vita.
but now im not able to use it now.
i reinstalled the app becuz of a update, but now when i open the app the current account the app is showing is "not found".
and when i go to save current account this shows up.
you can`t save this account : profile cannot be found
When i go to activate this device:
Activation data cannot be found. Check your connection/creditionals 
im on 3.60 with latest henkaku with working psn.
pls can any one help

**Comment by elpendor** [comment]
"Profile Not found" means exactly what it says.

Check if you have your id.dat file where it belongs and if it has an OID value. 

Trial accounts are not supported yet.

**Comment by psvita123** [comment]
Hello
my id.dat file is in the root of ux0
But what is the meaning of OID value?

**Comment by elpendor** [comment]
What values does it have?

**Comment by psvita123** [comment]
size is 0 bytes
value inside 0000

**Comment by elpendor** [comment]
There's your problem. 

Delete the file, it will rebuild itself after reboot.

**Comment by psvita123** [comment]
new problem;
yeah after reboot i guess the id.dat file got fixed and there were some correct values.
i went to ur app and clicked save current account
it said
"Profile was found but some files are missing"
Then when i go to unslave memory card it is successfull and then i press back button and again to no profile found. id.dat file also corrupt with 0000

**Comment by psvita123** [comment]
what now, i already tried the reboot method twice but first the id.dat file get fixed and the again corrupted

**Comment by elpendor** [comment]
>new problem;
yeah after reboot i guess the id.dat file got fixed and there were some correct values.
i went to ur app and clicked save current account
it said
"Profile was found but some files are missing"

"Profile was found but some files are missing" means any of the other files are missing. You need to login and succesfully activate an account before saving it. If you did that, the files will be there.

>Then when i go to unslave memory card it is successfull and then i press back button and again to no profile found. id.dat file also corrupt with 0000

Of course it will be empty, that's what unslaving the card does. It unslaves the card from your current profile. What are you unslaving the card for?

**Comment by psvita123** [comment]
My psn is signed in perfectly and my PS store is also working
Do u advise me to reset my device and try again?

**Comment by elpendor** [comment]
Did you activate the device or not?

**Comment by psvita123** [comment]
activate how by ur app or by going to ps vita settings

**Comment by elpendor** [comment]
Any of them. End result is the same.

**Comment by psvita123** [comment]
PROBLEM SOLVED!!!!!!!!
Thanks a thousand times.
i never knew developers were such helpful
I will close the issue.
Thanks again,
Best of luck!!!!!!
Release good apps like these whenever you get time!!!!!!

**Comment by elpendor** [comment]
No problem. Glad you got it to work.
